workflows:
  hello-world:


    triggering:
     events:
       - "push"
     branch_patterns:
       - pattern: 'main'
       - include: true
         source: true


    name: Hello world

    scripts:
      - name: Hello world
        script: echo 'change message'

      - name: CREATE ENV
        script: mkdir env

      - name: CREATE PROD.JSON
        script: echo '{"name":"${{vars.REGARD}}"}' > env/prod.json

