name: 01-FLUTTER-INSTALL
on:
  push:
    branches: [main]

jobs:
  flutter-masters-deploy:
    runs-on: macos-latest

    steps:
      - name: INSTALLING JAVA
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "11"

      - name: COPY .
        uses: actions/checkout@v4

      - name: INSTALL FLUTTER
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: FLUTTER TEST
        run: flutter test

      - name: FLUTTER ANALYZE
        run: flutter analyze

      - name: CREATE ENV
        run: mkdir env

      - name: CREATE DEV.JSON
        run: echo '{"name":${{vars.REGARD}}}' > dev.json
        working-directory: env

      - name: FLUTTER GENERATE APK
        run: flutter build apk --release --dart-define-from-file=env/dev.json

      - name: UPLOAD APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-for-test
          path: Built build/app/outputs/flutter-apk/app-release.apk
